name: game_parking
version: 2.0.1
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: Game Parking is a Rush Hour game. dartling is a domain model framework.
homepage: http://ondart.me/
documentation: http://goo.gl/LDhRwm
dependencies:
  browser: any
  dartling: any


